package pojo;
// Generated Oct 5, 2022 9:52:18 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Employee generated by hbm2java
 */
@ManagedBean
public class Employee  implements java.io.Serializable {


     private int idEmployee;
     private String name;
     private String username;
     private String password;
     private String type;

    public Employee() {
    }

    public Employee(int idEmployee, String name, String username, String password, String type) {
       this.idEmployee = idEmployee;
       this.name = name;
       this.username = username;
       this.password = password;
       this.type = type;
    }

    public void setType(String type) {
        this.type = type;
    }
   
    public int getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(int idEmployee) {
        this.idEmployee = idEmployee;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String validasiUser() {
        DAOLogin uDao = new DAOLogin();
        List<Employee> us = uDao.getBy(username, password);
        try {
            if (us != null) {
            name = us.get(0).name;
            username = us.get(0).username;
            password = us.get(0).password;
            return "LoginSuccses";
            } 
        } catch (Exception e) {
            System.out.println(e);
        }
        return "LoginFailed";
    }
    
        public String logout() {
	return "index";
    }

    public String getType() {
        return type;
    }
}


