package pojo;
// Generated Oct 5, 2022 9:52:18 PM by Hibernate Tools 4.3.1

import DAO.DAOProduct;
import java.util.List;
import javax.faces.bean.ManagedBean;





/**
 * Product generated by hbm2java
 */
@ManagedBean
public class Product  implements java.io.Serializable {


     private int idProduct;
     private String merk;
     private String series;
     private Long price;
     private Integer stock;

    public Product() {
    }

	
    public Product(int idProduct, String merk) {
        this.idProduct = idProduct;
        this.merk = merk;
    }
    public Product(int idProduct, String merk, String series, Long price, Integer stock) {
       this.idProduct = idProduct;
       this.merk = merk;
       this.series = series;
       this.price = price;
       this.stock = stock;
    }
   
    public int getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(int idProduct) {
        this.idProduct = idProduct;
    }
    public String getMerk() {
        return this.merk;
    }
    
    public void setMerk(String merk) {
        this.merk = merk;
    }
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    
    public String saveProduct() {
        DAOProduct product = new DAOProduct();
        product.addProduct(this);
        System.out.println(merk+series+price+stock);
        idProduct = 0;
        merk = "";
        series = "";
        price = null;
        stock=0;
        
        return "LoginSuccses";
    }

    public String deleteProduct() {
        DAOProduct product = new DAOProduct();
        product.deleteProduct(idProduct);
        System.out.println(merk);
        merk = "";
        price = null;
        series = "";
        stock = 0;
        return "LoginSuccses";
    }

    public List<Product> getbyid()
    { 
        DAOProduct pDao=new DAOProduct();
        List<Product> prod=pDao.getbyID(idProduct);
        merk=prod.get(0).merk;
        series=prod.get(0).series;
        price=prod.get(0).price;
        stock=prod.get(0).stock;
        return prod;
    }
    
    public String editpage(){
        DAOProduct pDao=new DAOProduct();
        List<Product> prod=pDao.getbyID(idProduct);
        merk=prod.get(0).merk;
        series=prod.get(0).series;
        price=prod.get(0).price;
        stock=prod.get(0).stock;
       return "edit";
    }

    public String getById() {
        DAOProduct product = new DAOProduct();
        List<Product> prod = product.getbyID(idProduct);
        try {
            if (prod != null) {
                merk=prod.get(0).merk;
                series=prod.get(0).series;
                price=prod.get(0).price;
                stock=prod.get(0).stock;
                return "LoginSuccses_search";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "LoginSuccses_ErorrSearch";
    }
   

public List<Product> getallrecords()
{
    DAOProduct pDao=new DAOProduct();
    List<Product> prod=pDao.retrieveProduct();
    return prod;
}

public List<Product> getallrecords_asc()
{
    DAOProduct pDao=new DAOProduct();
    List<Product> prod=pDao.retrieveProduct_bystock_asc();
    return prod;
}

public List<Product> getallrecords_desc()
{
    DAOProduct pDao=new DAOProduct();
    List<Product> prod=pDao.retrieveProduct_bystock_desc();
    return prod;
}

public String update()
{
    DAOProduct pDao=new DAOProduct();
    pDao.updateProduct(this);
    return "LoginSuccses";
}



}