package pojo;
// Generated Oct 5, 2022 9:52:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private int idTransactions;
     private Integer idEmployee;
     private Integer idProduct;
     private int totalOrder;
     private Long totalAmount;
     private String customerName;
     private Date transactionDate;

    public Transactions() {
    }

	
    public Transactions(int idTransactions, int totalOrder) {
        this.idTransactions = idTransactions;
        this.totalOrder = totalOrder;
    }
    public Transactions(int idTransactions, Integer idEmployee, Integer idProduct, int totalOrder, Long totalAmount, String customerName, Date transactionDate) {
       this.idTransactions = idTransactions;
       this.idEmployee = idEmployee;
       this.idProduct = idProduct;
       this.totalOrder = totalOrder;
       this.totalAmount = totalAmount;
       this.customerName = customerName;
       this.transactionDate = transactionDate;
    }
   
    public int getIdTransactions() {
        return this.idTransactions;
    }
    
    public void setIdTransactions(int idTransactions) {
        this.idTransactions = idTransactions;
    }
    public Integer getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Integer idEmployee) {
        this.idEmployee = idEmployee;
    }
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public int getTotalOrder() {
        return this.totalOrder;
    }
    
    public void setTotalOrder(int totalOrder) {
        this.totalOrder = totalOrder;
    }
    public Long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }




}


